console.log("Sama dengan\n==")
console.log("---------------")
console.log("Sama dengan/Tipe sama\n=== ")
console.log("---------------")
console.log("Tidak sama dengan\n!=")
console.log("---------------")
console.log("Tidak sama dengan/Tipe beda\n!==")
console.log("---------------")
console.log("Lebih besar/Sama\n>=")
console.log("---------------")
console.log("Lebih kecil/Sama\n<=")
console.log("---------------")
console.log("Lebih besar\n>")
console.log("---------------")
console.log("Lebih kecil\n<")
